# THE FIRST MGI FILE
MARKER chpos
ALLELE alt ref
EFFECT beta
PVALUE pval
WEIGHT N
PROCESS /path to mgi data/

#  THE SECOND BENYAMIN FILE
MARKER chpos
ALLELE A1 A2
EFFECT EFFECT_A1
PVALUE P
WEIGHT N
PROCESS /path to benyamin data/

# THE THIRD SARDINIA FILE
MARKER Snp
ALLELE EffectAllele  Non-effectAllele
EFFECT Beta
PVALUE Pvalue
WEIGHT N_individuals
PROCESS /path to sardinia data

#THE FOURTH BLSA FILE
MARKER SNP
ALLELE A1 A2
EFFECT BETA
PVALUE P
WEIGHT NMISS
PROCESS /path to blsa data

#THE  BELL INPUT FILE
MARKER chpos
ALLELE effectAllele otherAllele
EFFECT Beta
PVALUE P
WEIGHT N
PROCESS /path to bell data/

#THE ICM INPUT FILE
MARKER chpos
ALLELE Allele2 Allele1
EFFECT BETA
PVALUE Pvalue
WEIGHT N
PROCESS /path to icm data

OUTFILE METAl_analysis_results2.tbl
AVERAGEFREQ ON
MINMAXFREQ ON
ANALYZE

